name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Test and coverage
        run: npm test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@b116fb45f78819bd9484b2591be2ea124e94119d
        env:
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
